let rules = {
  start: "Is $subject $option ?", 
  subject: "love"
}

let scene = [];
scene[0] = "Is love LK_ a&spsp;need _LK or LK_ a&spsp;want _LK ?"

scene[1] = "Do I really need love or it is just my subjective craving. IB8 My mind is in an IB3 overwhelming heat, IB5 evaporating every rational thought. IB8 Logic is irrelevant here . IB8 All there left IB3 are IB2 impetuosity IB5 and doubt ."

scene[2] = "Ever since first sight, IB3 I have become the words written by god's IB3 pen. IB6 After that, everything  is IB2 unchangable and IB6 irreplaceable. IB8 Es IB8 muss IB8 sein. I  will  eventually IB3 fall IB3 in IB3 love IB6 with you. IB8 I long  know. IB6 Love is  destined IB6 and inevitable .  "
  
scene[3] = "I am trying to water the plant, IB5 day by day IB5 by  day. IB8 Perhaps one day, IB3 it  will  grow  up. IB6 Flowers will blossom IB4 and apples will drop.  IB8 What welcomes me IB3 is the IB2 long IB2 awaited IB2 delight. IB8 And the next  plants IB5 will be watered by us. IB8 Love, IB5 I wish it is a&spsp;cycle ."
  
// scene[4] = "For  doubt  and  my  love.         By  Jonathan  Chan,     advised  by  Danial  Howe."


let sceneTrigger = [["a need", "a want"], ["impetuosity", "doubt"], ["destined", "inevitable"], ["cycle"], []];

let instruction;

let instructionAni = ["red", "purple"];
let instructionIndex = 0;
let instructionBoo = true;




let wordset = []
wordset[0] = {set: "goal", leftPicks: ["attach" ,"longTime" ,"noble" ,"freedom"], antonyms:["burden"], side: true, score: 2}; 
wordset[1] = {set: "longTime", leftPicks: ["goal" ,"grace" ,"settle" ,"attach" ,"true"], antonyms:["shortTime" ,"weak"], side: true, score: 1}; 
wordset[2] = {set: "entertain", leftPicks: ["delight" ,"freedom" ,"noble" ,"true" ,"great"], antonyms:["bored" ,"overwhelm"], side: true, score: -3}; 
wordset[3] = {set: "attach", leftPicks: ["goal" ,"attention" ,"freedom" ,"settle"], antonyms:["indifferent"], side: true, score: 3}; 
wordset[4] = {set: "impulse", leftPicks: ["grace" ,"freedom" ,"true" ,"longTime" ,"entertain"], antonyms:["overwhelm" ,"regret"], side: true, score: -2}; 
wordset[5] = {set: "delight", leftPicks: ["impulse" ,"longTime" ,"true" ,"great" ,"entertain"], antonyms:["pain" ,"regret"], side: true, score: -3}; 
wordset[6] = {set: "attention", leftPicks: ["noble" ,"goal" ,"grace"], antonyms:["indifferent"], side: true, score: 2}; 
wordset[7] = {set: "noble", leftPicks: ["goal" ,"attach" ,"true" ,"longTime"], antonyms:["nonNoble"], side: true, score: 2}; 
wordset[8] = {set: "grace", leftPicks: ["delight" ,"true" ,"longTime"], antonyms:["worthless"], side: true, score: 0}; 
wordset[9] = {set: "true", leftPicks: ["longTime" ,"freedom" ,"noble" ,"settle"], antonyms:["fake"], side: true, score: 1}; 
wordset[10] = {set: "freedom", leftPicks: ["goal" ,"longTime" ,"grace" ,"entertain"], antonyms:["slavery"], side: true, score: -3}; 
wordset[11] = {set: "settle", leftPicks: ["freedom" ,"attach" ,"attention" ,"goal"], antonyms:["weak", "indifferent"], side: true, score: 1}; 
wordset[12] = {set: "great", leftPicks: ["delight" ,"longTime" ,"entertain" ,"true"], antonyms:["worthless" ,"weak"], side: true, score: -1}; 
wordset[13] = {set: "burden", leftPicks: ["attach" ,"longTime" ,"noble"], antonyms:["goal"], side: false, score: 2}; 
wordset[14] = {set: "bored", leftPicks: ["attach" ,"freedom" ,"delight" ,"settle"], antonyms:["entertain"], side: false, score: 1}; 
wordset[15] = {set: "indifferent", leftPicks: ["attention" ,"grace" ,"goal" ,"impulse"], antonyms:["attach", "settle"], side: false, score: 2}; 
wordset[16] = {set: "slavery", leftPicks: ["longTime" ,"noble" ,"settle" ,"great"], antonyms:["freedom"], side: false, score: 3}; 
wordset[17] = {set: "regret", leftPicks: ["noble" ,"true" ,"impulse" ,"grace"], antonyms:["delight" ,"entertain"], side: false, score: -1}; 
wordset[18] = {set: "nonNoble", leftPicks: ["goal" ,"freedom" ,"attention" ,"impulse"], antonyms:["noble"], side: false, score: -1}; 
wordset[19] = {set: "worthless", leftPicks: ["true" ,"entertain" ,"settle"], antonyms:["grace"], side: false, score: -3}; 
wordset[20] = {set: "pain", leftPicks: ["true" ,"longTime" ,"goal" ,"attention"], antonyms:["delight"], side: false, score: 2}; 
wordset[21] = {set: "weak", leftPicks: ["goal" ,"noble" ,"grace" ,"settle"], antonyms:["settle" ,"longTime"], side: false, score: 0}; 
wordset[22] = {set: "fake", leftPicks: ["attention" ,"freedom" ,"settle" ,"goal"], antonyms:["true"], side: false, score: -2}; 
wordset[23] = {set: "overwhelm", leftPicks: ["attach" ,"grace" ,"noble" ,"freedom"], antonyms:["entertain" ,"impulse"], side: false, score: -3}; 
wordset[24] = {set: "shortTime", leftPicks: ["entertain" ,"impulse" ,"great"], antonyms:["longTime"], side: false, score: -2};  
wordset[25] = {set: "need", leftPicks: ["goal", "attach", "attention", "noble", "freedom"], antonyms: ["want"], side: true, score: 4};
wordset[26] = {set: "want", leftPicks: ["entertain", "impulse", "noble", "true"], antonyms: ["need"], side: false, score: -4};
wordset[27] = {set: "contradiction", leftPicks: ["attention", "impulse", "grace", "true"], antonyms: ["need"], side: false, score: 0};



let wordList = [];

wordList[0] = {word: "a pursuit", subject: "pursuit", set: "goal", side: true}; 
wordList[1] = {word: "a goal", subject: "a goal", set: "goal", side: true}; 
wordList[2] = {word: "a calling", subject: "calling", set: "goal", side: true}; 
wordList[3] = {word: "a life long", subject: "a lifework", set: "longTime", side: true}; 
wordList[4] = {word: "an avocation", subject: "avocation", set: "entertain", side: true}; 
wordList[5] = {word: "a recreation", subject: "recreation", set: "entertain", side: true}; 
wordList[6] = {word: "an excitment", subject: "excitment", set: "entertain", side: true}; 
wordList[7] = {word: "an attachment", subject: "attachment", set: "attach", side: true}; 
wordList[8] = {word: "a feeling", subject: "feeling", set: "impulse", side: true}; 
wordList[9] = {word: "a pleasure", subject: "pleasure", set: "delight", side: true}; 
wordList[10] = {word: "energatic", subject: "energy", set: "impulse", side: true}; 
wordList[11] = {word: "conscious", subject: "consciousness", set: "attach", side: true}; 
wordList[12] = {word: "an attention", subject: "attention", set: "attention", side: true}; 
wordList[13] = {word: "esteem", subject: "esteem", set: "attention", side: true}; 
wordList[14] = {word: "respect", subject: "respect", set: "noble", side: true}; 
wordList[15] = {word: "a passion", subject: "passion", set: "impulse", side: true}; 
wordList[16] = {word: "a dignity", subject: "dignity", set: "noble", side: true}; 
wordList[17] = {word: "a grace", subject: "grace", set: "grace", side: true}; 
wordList[18] = {word: "immortal", subject: "immortality", set: "longTime", side: true}; 
wordList[19] = {word: "a credit", subject: "credit", set: "noble", side: true}; 
wordList[20] = {word: "a reality", subject: "reality", set: "true", side: true}; 
wordList[21] = {word: "significant", subject: "what's signficant", set: "noble", side: true}; 
wordList[22] = {word: "a fortune", subject: "fortune", set: "grace", side: true}; 
wordList[23] = {word: "a blessing", subject: "blessing", set: "grace", side: true}; 
wordList[24] = {word: "pure", subject: "purity", set: "noble", side: true}; 
wordList[25] = {word: "complete", subject: "completion", set: "longTime", side: true}; 
wordList[26] = {word: "a virtue", subject: "a virtue", set: "noble", side: true}; 
wordList[27] = {word: "honest", subject: "honesty", set: "true", side: true}; 
wordList[28] = {word: "faithful", subject: "faithfulness", set: "true", side: true}; 
wordList[29] = {word: "loyal", subject: "loyalty", set: "noble", side: true}; 
wordList[30] = {word: "equal", subject: "equality", set: "noble", side: true}; 
wordList[31] = {word: "sincere", subject: "sincereness", set: "noble", side: true}; 
wordList[32] = {word: "genuine", subject: "what's genuine", set: "true", side: true}; 
wordList[33] = {word: "free", subject: "freedom", set: "freedom", side: true}; 
wordList[34] = {word: "reward", subject: "reward", set: "attach", side: true}; 
wordList[35] = {word: "a save house", subject: "a save house", set: "settle", side: true}; 
wordList[36] = {word: "joy", subject: "joy", set: "delight", side: true}; 
wordList[37] = {word: "perfect", subject: "perfection", set: "great", side: true}; 
wordList[38] = {word: "extraordinary", subject: "extraordinariness", set: "great", side: true}; 
wordList[39] = {word: "settling", subject: "settlement", set: "settle", side: true}; 
wordList[40] = {word: "bloom", subject: "the blooming", set: "great", side: true}; 
wordList[41] = {word: "the peak", subject: "the peak", set: "great", side: true}; 
wordList[42] = {word: "constructive", subject: "construciveness", set: "settle", side: true}; 
wordList[43] = {word: "reciprocal", subject: "reciprocity", set: "settle", side: true}; 
wordList[44] = {word: "an acheivement", subject: "acheivement", set: "goal", side: true}; 
wordList[45] = {word: "commencement", subject: "commencement", set: "goal", side: true}; 
wordList[46] = {word: "the dawn", subject: "the dawn", set: "great", side: true}; 
wordList[47] = {word: "a poem", subject: "a poem", set: "true", side: true}; 
wordList[48] = {word: "external", subject: "externality", set: "longTime", side: true}; 
wordList[49] = {word: "a goodwill", subject: "goodwill", set: "grace", side: true}; 
wordList[50] = {word: "an open door", subject: "an open door", set: "freedom", side: true}; 
wordList[51] = {word: "elegant", subject: "what's elegant", set: "great", side: true}; 
wordList[52] = {word: "harmony", subject: "harmony", set: "settle", side: true}; 
wordList[53] = {word: "a wonder", subject: "a wonder", set: "great", side: true}; 
wordList[54] = {word: "a hope", subject: "hope", set: "grace", side: true}; 
wordList[55] = {word: "a burden", subject: "a burden", set: "burden", side: false}; 
wordList[56] = {word: "a duty", subject: "a duty", set: "burden", side: false}; 
wordList[57] = {word: "a charge", subject: "a charge", set: "burden", side: false}; 
wordList[58] = {word: "the end", subject: "the end", set: "bored", side: false}; 
wordList[59] = {word: "boredom", subject: "boredom", set: "bored", side: false}; 
wordList[60] = {word: "a work", subject: "working", set: "burden", side: false}; 
wordList[61] = {word: "a fatigue", subject: "fatigue", set: "burden", side: false}; 
wordList[62] = {word: "a detachment", subject: "detachment", set: "bored", side: false}; 
wordList[63] = {word: "a routine", subject: "a routine", set: "bored", side: false}; 
wordList[64] = {word: "lethargy", subject: "lethargy", set: "indifferent", side: false}; 
wordList[65] = {word: "forced", subject: "which's forced", set: "slavery", side: false}; 
wordList[66] = {word: "a regret", subject: "regret", set: "regret", side: false}; 
wordList[67] = {word: "alienation", subject: "alienation", set: "indifferent", side: false}; 
wordList[68] = {word: "dishonor", subject: "dishonor", set: "nonNoble", side: false}; 
wordList[69] = {word: "criticism", subject: "criticism", set: "indifferent", side: false}; 
wordList[70] = {word: "neglectable", subject: "what's neglected", set: "indifferent", side: false}; 
wordList[71] = {word: "fear", subject: "fear", set: "slavery", side: false}; 
wordList[72] = {word: "a distance", subject: "a distance", set: "indifferent", side: false}; 
wordList[73] = {word: "worthless", subject: "what doesn't worth it", set: "worthless", side: false}; 
wordList[74] = {word: "impractical", subject: "what's impractical", set: "worthless", side: false}; 
wordList[75] = {word: "inefficient", subject: "inefficiency", set: "worthless", side: false}; 
wordList[76] = {word: "evil", subject: "what's evil", set: "nonNoble", side: false}; 
wordList[77] = {word: "useless", subject: "what's useless", set: "worthless", side: false}; 
wordList[78] = {word: "harmful", subject: "harm", set: "pain", side: false}; 
wordList[79] = {word: "a curse", subject: "curse", set: "pain", side: false}; 
wordList[80] = {word: "contaminated", subject: "contamination", set: "nonNoble", side: false}; 
wordList[81] = {word: "corruption", subject: "corruption", set: "nonNoble", side: false}; 
wordList[82] = {word: "irresponsible", subject: "being irresponsible", set: "nonNoble", side: false}; 
wordList[83] = {word: "a scam", subject: "a scam", set: "nonNoble", side: false}; 
wordList[84] = {word: "weak", subject: "my weakness", set: "weak", side: false}; 
wordList[85] = {word: "fabricated", subject: "what's fabricated", set: "fake", side: false}; 
wordList[86] = {word: "pretentious", subject: "being pretentious", set: "fake", side: false}; 
wordList[87] = {word: "captivity", subject: "being captivated", set: "slavery", side: false}; 
wordList[88] = {word: "capitalistic", subject: "capitalism", set: "slavery", side: false}; 
wordList[89] = {word: "slavery", subject: "slavery", set: "slavery", side: false}; 
wordList[90] = {word: "dependent", subject: "being dependent", set: "", side: false}; 
wordList[91] = {word: "vulnerable", subject: "what's vulnerable", set: "weak", side: false}; 
wordList[92] = {word: "defenseless", subject: "what's defenseless", set: "weak", side: false}; 
wordList[93] = {word: "immature", subject: "being immature", set: "regret", side: false}; 
wordList[94] = {word: "sacrifice", subject: "sacrifice", set: "pain", side: false}; 
wordList[95] = {word: "repeatative", subject: "repeating", set: "bored", side: false}; 
wordList[96] = {word: "overflowed", subject: "what's overflowing", set: "overwhelm", side: false}; 
wordList[97] = {word: "an exploit", subject: "exploiting", set: "nonNoble", side: false}; 
wordList[98] = {word: "a failure", subject: "failure", set: "regret", side: false}; 
wordList[99] = {word: "the sunset", subject: "the sunset", set: "shortTime", side: false}; 
wordList[100] = {word: "fictional", subject: "fiction", set: "fake", side: false}; 
wordList[101] = {word: "a fantasy", subject: "what's I fantasize", set: "fake", side: false}; 
wordList[102] = {word: "a myth", subject: "a myth", set: "fake", side: false}; 
wordList[103] = {word: "indifferent", subject: "indifference", set: "indifferent", side: false}; 
wordList[104] = {word: "a lie", subject: "a lie", set: "fake", side: false}; 
wordList[105] = {word: "indulgent", subject: "indulgent", set: "regret", side: false}; 
wordList[106] = {word: "spoiling", subject: "spoiling", set: "regret", side: false}; 
wordList[107] = {word: "a karma", subject: "a karma", set: "pain", side: false}; 
wordList[108] = {word: "a coincident", subject: "coincident", set: "worthless", side: false}; 
wordList[109] = {word: "fragile", subject: "what's fragile", set: "weak", side: false};  

wordList[110] = {word: "a need", subject: "need", set: "need", side: true};  
wordList[111] = {word: "a want", subject: "want", set: "want", side: false};  
wordList[112] = {word: "love", subject: 'love', set: "delight", side: true};

wordList[113] =  {word: "purposeful", subject: "a purpose", set: "goal", side: true}; 
wordList[114] =  {word: "persistent", subject: "persistence", set: "goal", side: true}; 
wordList[115] =  {word: "goal", subject: "our goal", set: "goal", side: true} ;
wordList[116] =  {word: "longlasting", subject: "what's longlasting", set: "longTime", side: true} ;
wordList[117] =  {word: "lifelong", subject: "what's lifelong", set: "longTime", side: true} ;
wordList[118] =  {word: "our journey", subject: "our journey", set: "longTime", side: true} ;
wordList[119] =  {word: "our eternity", subject: "our eternity", set: "longTime", side: true}; 
wordList[120] =  {word: "entertaining", subject: "entertainment", set: "entertain", side: true} ;
wordList[121] =  {word: "relaxing", subject: "relaxation", set: "entertain", side: true} ;
wordList[122] =  {word: "enjoyment", subject: "enjoyment", set: "entertain", side: true} ;
wordList[123] =  {word: "recreation", subject: "recreation", set: "entertain", side: true}; 
wordList[124] =  {word: "connecting", subject: "connection", set: "attach", side: true} ;
wordList[125] =  {word: "heart-sharing", subject: "heart-sharing", set: "attach", side: true} ;
wordList[126] =  {word: "attachment", subject: "attachment", set: "attach", side: true} ;
wordList[127] =  {word: "company", subject: "company", set: "attach", side: true} ;
wordList[128] =  {word: "passionate", subject: "passion", set: "impulse", side: true}; 
wordList[129] =  {word: "energetic", subject: "energy", set: "impulse", side: true} ;
wordList[130] =  {word: "passion", subject: "passion", set: "impulse", side: true} ;
wordList[131] =  {word: "energy", subject: "energy", set: "impulse", side: true} ;
wordList[132] =  {word: "delightful", subject: "delight", set: "delight", side: true} ;
wordList[133] =  {word: "pleasing", subject: "pleasure", set: "delight", side: true} ;
wordList[134] =  {word: "glee", subject: "glee", set: "delight", side: true} ;
wordList[135] =  {word: "pleasure", subject: "pleasure", set: "delight", side: true} ;
wordList[136] =  {word: "admiring", subject: "what's admirable", set: "attention", side: true} ;
wordList[137] =  {word: "attention", subject: "attention", set: "attention", side: true} ;
wordList[138] =  {word: "noble", subject: "what's noble", set: "noble", side: true} ;
wordList[139] =  {word: "a virtue", subject: "virtue", set: "noble", side: true} ;
wordList[140] =  {word: "graceful", subject: "grace", set: "grace", side: true} ;
wordList[141] =  {word: "elegant", subject: "what's elegant", set: "grace", side: true} ;
wordList[142] =  {word: "blessing", subject: "blessing", set: "grace", side: true} ;
wordList[143] =  {word: "honest", subject: "being honest", set: "true", side: true} ;
wordList[144] =  {word: "truthful", subject: "being truthful", set: "true", side: true} ;
wordList[145] =  {word: "frank", subject: "frankness", set: "true", side: true} ;
wordList[146] =  {word: "genuineness", subject: "genuineness", set: "true", side: true} ;
wordList[147] =  {word: "free", subject: "freedom", set: "freedom", side: true} ;
wordList[148] =  {word: "liberating", subject: "liberation", set: "freedom", side: true} ;
wordList[149] =  {word: "freedom", subject: "freedom", set: "freedom", side: true} ;
wordList[150] =  {word: "relief", subject: "relief", set: "freedom", side: true} ;
wordList[151] =  {word: "settling", subject: "settlement", set: "settle", side: true} ;
wordList[152] =  {word: "harmonious", subject: "harmony", set: "settle", side: true} ;
wordList[153] =  {word: "safety", subject: "safety", set: "settle", side: true} ;
wordList[154] =  {word: "harmony", subject: "harmony", set: "settle", side: true}; 
wordList[155] =  {word: "settlement", subject: "settlement", set: "settle", side: true} ;
wordList[156] =  {word: "remarkable", subject: "the remarkable thing we make", set: "great", side: true} ;
wordList[157] =  {word: "excellent", subject: "excellence", set: "great", side: true} ;
wordList[158] =  {word: "greatness", subject: "greatness", set: "great", side: true} ;
wordList[159] =  {word: "importance", subject: "importance", set: "great", side: true}; 
wordList[160] =  {word: "onerous", subject: "what's onerous", set: "burden", side: true} ;
wordList[161] =  {word: "exhausting", subject: "waht's exhausting", set: "burden", side: true} ;
wordList[162] =  {word: "burden", subject: "burden", set: "burden", side: true} ;
wordList[163] =  {word: "charge", subject: "charge", set: "burden", side: true} ;
wordList[164] =  {word: "load", subject: "load", set: "burden", side: true} ;
wordList[165] =  {word: "boring", subject: "boredom", set: "bored", side: true} ;
wordList[166] =  {word: "dull", subject: "dullnexx", set: "bored", side: true} ;
wordList[167] =  {word: "boredom", subject: "boredom", set: "bored", side: true} ;
wordList[168] =  {word: "ennui", subject: "ennui", set: "bored", side: true} ;
wordList[169] =  {word: "routine", subject: "routine", set: "bored", side: true} ;
wordList[170] =  {word: "detached", subject: "detachment", set: "indifferent", side: true} ;
wordList[171] =  {word: "isolated", subject: "isolation", set: "indifferent", side: true} ;
wordList[172] =  {word: "indifference", subject: "indifference", set: "indifferent", side: true} ;
wordList[173] =  {word: "isolation", subject: "isolation", set: "indifferent", side: true} ;
wordList[174] =  {word: "captive", subject: "captivity", set: "slavery", side: true} ;
wordList[175] =  {word: "imprisoned", subject: "being imprisoned", set: "slavery", side: true} ;
wordList[176] =  {word: "suppressed", subject: "being suppressed", set: "slavery", side: true} ;
wordList[177] =  {word: "slavery", subject: "slavery", set: "slavery", side: true} ;
wordList[178] =  {word: "bondage", subject: "bondage", set: "slavery", side: true} ;
wordList[179] =  {word: "regretful", subject: "regret", set: "regret", side: true} ;
wordList[180] =  {word: "upset", subject: "upset", set: "regret", side: true} ;
wordList[181] =  {word: "regret", subject: "regret", set: "regret", side: true} ;
wordList[182] =  {word: "evil", subject: "evil", set: "nonNoble", side: true} ;
wordList[183] =  {word: "hatred", subject: "hatred", set: "nonNoble", side: true} ;
wordList[184] =  {word: "contimination", subject: "contimination", set: "nonNoble", side: true} ;
wordList[185] =  {word: "pointless", subject: "what's pointless", set: "worthless", side: true} ;
wordList[186] =  {word: "cheap", subject: "what's cheap", set: "worthless", side: true} ;
wordList[187] =  {word: "useless", subject: "what's useless", set: "worthless", side: true} ;
wordList[188] =  {word: "waste", subject: "waste", set: "worthless", side: true} ;
wordList[189] =  {word: "painful", subject: "pain", set: "pain", side: true} ;
wordList[190] =  {word: "harmful", subject: "harm", set: "pain", side: true} ;
wordList[191] =  {word: "pain", subject: "pain", set: "pain", side: true} ;
wordList[192] =  {word: "fragile", subject: "what's fragile", set: "weak", side: true} ;
wordList[193] =  {word: "weak", subject: "what's weak", set: "weak", side: true} ;
wordList[194] =  {word: "powerless", subject: "what's powerless", set: "weak", side: true} ;
wordList[195] =  {word: "flaw", subject: "our flaw", set: "weak", side: true} ;
wordList[196] =  {word: "blemish", subject: "blemish thing", set: "weak", side: true} ;
wordList[197] =  {word: "illusory", subject: "an illusion", set: "fake", side: true} ;
wordList[198] =  {word: "dishonest", subject: "being dishonest", set: "fake", side: true} ;
wordList[199] =  {word: "fabricated", subject: "what's fabricated", set: "fake", side: true} ;
wordList[200] =  {word: "lie", subject: "a lie", set: "fake", side: true} ;
wordList[201] =  {word: "unstoppable", subject: "what can't be stopped", set: "overwhelm", side: true} ;
wordList[202] =  {word: "destructive", subject: "destruction", set: "overwhelm", side: true} ;
wordList[203] =  {word: "devastating", subject: "devastation", set: "overwhelm", side: true} ;
wordList[204] =  {word: "wild", subject: "wild thing", set: "overwhelm", side: true} ;
wordList[205] =  {word: "unstoppable destruction", subject: "destruction", set: "overwhelm", side: true} ;
wordList[206] =  {word: "destruction", subject: "destruction", set: "overwhelm", side: true};
wordList[207] =  {word: "biased", subject: "what's bias", set: "nonNoble", side: true};
wordList[208] =  {word: "rational", subject: "rationality", set: "noble", side: true};
wordList[209] =  {word: "magic", subject: "magic", set: "great", side: true};
wordList[210] =  {word: "fantasy", subject: "fantasy", set: "fake", side: true};
wordList[211] =  {word: "fate", subject: "fate", set: "bored", side: true};
wordList[212] =  {word: "delight", subject: "delight", set: "delight", side: true};
wordList[213] =  {word: "contradiction", subject: "contradiction", set: "contradiction", side: true};


